# Generated by Django 3.2.11 on 2022-01-13 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import files.models
import files.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('old_file_name', models.CharField(max_length=128)),
                ('file', models.FileField(default=None, upload_to=files.models.user_directory_path, validators=[files.validators.validate_file])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'files',
            },
        ),
    ]
