# Generated by Django 3.2.11 on 2022-01-14 01:51

from django.db import migrations, models
import files.models
import files.validators


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=files.models.user_directory_path, validators=[files.validators.validate_file]),
        ),
    ]
